### ISSUE TITLE
setup CICD for main branch

### ISSUE THREAD

**Issue by extreme4all** [Bot-detector/Bot-detector-Twitter#11] opened 2021-11-19 19:30 UTC
as a developer i want to have the CICD setup for deployments to the main server

**Comment by ThorntonMatthewD** [comment] 2021-11-20 16:12
This is mostly setup with c2d48652e07926efb93b5a83102f8bdece4a2bc6, ad82fbfc44de0907af5a3634ea18cefe9cacf403 and f9a871b1ad28bbc1f0e956fadf25c48f774b6166

## To fully get it working we need to:
- [ ]  Add in easter_eggs.py contents to either the repo secrets or host it on the build server. If we go with the latter we need to have a `cp /path/to/easter_eggs.py ./easter_eggs.py` command in our workflows.
- [ ]  Ensure the app is disabled wherever it is currently running.
- [ ]  Uncomment lines 49-53 in [this file](https://github.com/Bot-detector/Bot-detector-Twitter/blob/develop/prod-deploy.yaml)

**Comment by Ferrariic** [comment] 2021-11-20 16:16
Prior to launching it, just let me know so I can stop my pc hosting of the twitter bot

**Comment by extreme4all** [comment] 2021-11-20 20:05
@ThorntonMatthewD please link pull request when commiting

**Comment by ThorntonMatthewD** [comment] 2021-11-20 23:08
The issue isn't quite fully resolved.

We've only made it this far:
- [ X ]  Add in easter_eggs.py contents
- [ ] Ensure the app is disabled wherever it is currently running. (Ferrariic can do this whenever he wakes up)
- [ ]  Uncomment lines 49-53 in this file (This was the commit I was going to reference to close the issue)

**Closed as completed** 2021-11-22 14:58 UTC
